# packages in environment at C:\ProgramData\Anaconda3\envs\FOTECPFTL:
#
# Name                    Version                   Build  Channel
blas                      1.0                         mkl  
ca-certificates           2019.5.15                     0  
certifi                   2019.6.16                py37_0  
icc_rt                    2019.0.0             h0cc432a_1  
icu                       58.2                 ha66f8fd_1  
intel-openmp              2019.4                      245  
jpeg                      9b                   hb83a4c4_2  
libpng                    1.6.37               h2a8f88b_0  
mkl                       2019.4                      245  
mkl_fft                   1.0.12           py37h14836fe_0  
mkl_random                1.0.2            py37h343c172_0  
numpy                     1.16.4           py37h19fb1c0_0  
numpy-base                1.16.4           py37hc3f5095_0  
openssl                   1.1.1c               he774522_1  
pint                      0.9                      py37_2    conda-forge
pip                       19.1.1                   py37_0  
pyqt                      5.9.2            py37h6538335_2  
pyqtgraph                 0.10.0           py37h28b3542_3  
pyserial                  3.4                      py37_0  
python                    3.7.3                h8c8aaf0_1  
pyvisa                    1.9.1                 py37_1000    conda-forge
pyvisa-py                 0.3.1                    pypi_0    pypi
pyyaml                    5.1              py37he774522_0  
qt                        5.9.7            vc14h73c81de_0  
setuptools                41.0.1                   py37_0  
sip                       4.19.8           py37h6538335_0  
sqlite                    3.28.0               he774522_0  
vc                        14.1                 h0510ff6_4  
vs2015_runtime            14.15.26706          h3a45250_4  
wheel                     0.33.4                   py37_0  
wincertstore              0.2                      py37_0  
yaml                      0.1.7                hc54c509_2  
zlib                      1.2.11               h62dcd97_3  
