DAQ:
  name: Real
  port: COM9

scan:
  start: 0V # Cant be below 0, cant be above 3.3
  stop: 3.3V #
  num_steps: 100
  delay: 0.1s
  channel_out: 0
  channel_in: 0

monitor:
  channel_in: 0
  samples: 100 # number of points
  delay: 0.1s  # time interval between steps

experiment:
  resistance: 100 ohm
  save_file: IV_data
  save_meta: IV_Meta
  save_directory: D:\Data\Fotec\2019-06-28
